### ISSUE TITLE
Providing a config file to the Docker image

### ISSUE THREAD

**Issue by ernsheong** [gambol99/keycloak-proxy#274]
Hi there, sorry if this is something obvious that I missed.

Looks like the only way to pass configs to Docker is via the `args` config in docker-compose?

```
- name: keycloak-proxy
  image: quay.io/gambol99/keycloak-proxy:latest
  args:
  - --enable-forwarding=true
  - --forwarding-username=projecta
```

Is there a way to pass the JSON/yaml file directly via docker-compose?
