### ISSUE TITLE
Cannot contact discovery URL as string is not passed correctly.

### ISSUE THREAD

**Issue by howels** [gambol99/keycloak-proxy#417]
Running this inside Kubernetes with KeyCloak. Have keycloak as an externally available service and pointing keycloak-proxy to that URL, however when supplying the URL with suffix ".well-known/openid-configuration" the service cannot reach the URL:

````
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak-proxy
  namespace: proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak-proxy
      annotations:
        repository: https://github.com/gambol99/keycloak-proxy
    spec:
      containers:
        - name: keycloak-proxy
          image: quay.io/gambol99/keycloak-proxy:v2.3.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8000
          args:
            - --client-id=test
            - --discovery-url=http://test.example.com/auth/realms/freeipa/.well-known/openid-configuration
            - --enable-default-deny=false
            - --enable-json-logging=true
            - --enable-logging=true
            # - --enable-request-id=true
            - --enable-security-filter=true
            - --http-only-cookie=true
            - --listen=:8000
            # - --preserve-host=true
            - --redirection-url=http://automatix-1-f4.ngci.lab.vce.com
            - --resources=uri=/*|roles=admin
            - --skip-client-id=true
            - --upstream-url=http://httpbin.http1:8000
            - --secure-cookie=false
            - --verbose=true
````

Like this the suffix ".well-known/openid-configuration" is ignored:
```
{"level":"info","ts":1536165905.8208709,"caller":"keycloak-proxy/server.go:682","msg":"attempting to retrieve configuration discovery url","url":"http://test.example.com/auth/realms/freeipa","timeout":"30s"}
{"level":"warn","ts":1536165905.8221016,"caller":"keycloak-proxy/server.go:688","msg":"failed to get provider configuration from discovery","error":"EOF"}
````

If I attempt to quote the string in single-quotes ('http://test.example.com/auth/realms/freeipa/.well-known/openid-configuration') then I get another error:
````
{"level":"warn","ts":1536165349.6460118,"caller":"keycloak-proxy/server.go:659","msg":"failed to get provider configuration from discovery","error":"parse \\'http://test.example.com/auth/realms/freeipa/.well-known/openid-configuration\\'/.well-known/openid-configuration: first path segment in URL cannot contain colon"}

````
